### ISSUE TITLE
error: Cannot make a constant an alias

### ISSUE THREAD

**Issue by holtzermann17** [jadler/brazilian-holidays#2]
Here's the backtrace when I try to run `(require 'brazilian-holidays)`.

*****

Debugger entered--Lisp error: (error "Cannot make a constant an alias")
  defvaralias(nil nil nil)
  byte-code("\306\300\307\310\311DD\312\313\314\315\316&\7\210\10\203\30\0\317\11\320\"\21\306\302\307\310\321DD\322\313\314\315\316&\7\210\n\2030\0\317\11\323\"\21\306\303..." [brazilian-holidays-ac-holidays brazilian-holidays--local-holidays brazilian-holidays-al-holidays brazilian-holidays-am-holidays brazilian-holidays-ap-holidays brazilian-holidays-ba-holidays custom-declare-variable funcall function #f(compiled-function () #<bytecode 0x1e0000171e91>) "Regional holidays and commemorative dates for Acre..." :type boolean :group brazilian-holidays append ((holiday-fixed 1 23 "Dia do Evangélico") (holiday-fixed 5 15 "Aniversário do Acre") (holiday-float 9 5 "Dia do Comércio") (holiday-fixed 11 17 "Assinatura do Tratado de Petrópolis")) #f(compiled-function () #<bytecode 0x1e0000171e91>) "Regional holidays and commemorative dates for Alag..." ((holiday-fixed 6 24 "São João") (holiday-fixed 6 29 "São Pedro") (holiday-fixed 9 16 "Emancipação Política de Alagoas") (holiday-fixed 11 20 "Consciência Negra")) #f(compiled-function () #<bytecode 0x1e0000171e91>) "Regional holidays and commemorative dates for Amaz..." ((holiday-fixed 9 5 "Elevação do Amazonas à categoria de província") (holiday-fixed 11 20 "Consciência Negra") (holiday-fixed 12 8 "Dia de Nossa Senhora da Conceição")) #f(compiled-function () #<bytecode 0x1e0000171e91>) "Regional holidays and commemorative dates for Amap..." ((holiday-fixed 3 19 "Dia de São José") (holiday-fixed 7 25 "São Tiago") (holiday-fixed 10 5 "Criação do Estado do Amapá") (holiday-fixed 11 20 "Consciência Negra")) #f(compiled-function () #<bytecode 0x1e0000171e91>) "Regional holidays and commemorative dates for Bahi..." ((holiday-fixed 7 2 "Independência da Bahia")) brazilian-holidays-rj-holidays #f(compiled-function () #<bytecode 0x1e0000171e91>) "Regional holidays and commemorative dates for Rio ..." ((holiday-fixed 1 20 "São Sebastião") (holiday-easter-etc -47 "Carnaval") (holiday-easter-etc -46 "Quarta-feira de cinzas") (holiday-fixed 4 23 "São Jorge") (holiday-float 10 1 3 "Dia do Comércio") (holiday-fixed 11 20 "Consciência Negra")) brazilian-holidays-sp-holidays #f(compiled-function () #<bytecode 0x1e0000171e91>) "Regional holidays and commemorative dates for São ..." ((holiday-fixed 7 9 "Dia da Revolução Constitucionalista")) brazilian-holidays-bh-holidays #f(compiled-function () #<bytecode 0x1e0000171e91>) "Regional holidays and commemorative dates for Belo..." ((holiday-easter-etc -47 "Carnaval") (holiday-fixed 8 15 "Dia da Assunção de Nossa Senhora") (holiday-fixed 12 8 "Dia da Imaculada Conceição")) brazilian-holidays-mg-holidays #f(compiled-function () #<bytecode 0x1e0000171e91>) "Regional holidays and commemorative dates for Mina..." ((holiday-easter-etc -47 "Carnaval") (holiday-fixed 4 21 "Data Magna de Minas Gerais") (holiday-fixed 8 15 "Dia da Assunção de Nossa Senhora") (holiday-fixed 12 8 "Dia da Imaculada Conceição")) defvaralias nil (saved-value saved-variable-comment) put make-obsolete-variable ...] 12)
  require(brazilian-holidays)
  eval((require 'brazilian-holidays) t)
  eval-expression((require 'brazilian-holidays) nil nil 127)
  funcall-interactively(eval-expression (require 'brazilian-holidays) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)

**Comment by jadler** [comment]
@holtzermann17 thanks for reporting, I didn't noticed this error on my system.

I fixed the issue and removed the obsoletes variables, or in this case, the obsoletes constants.
